remote_theme: bagustris/primer2-theme
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: My Site
description: A site built with primer2-theme

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
